
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fariz
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbPBalok = new javax.swing.JTextField();
        tbLBalok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbTBalok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BtnBalok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tbPKubus = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnKubus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tbJBola = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        btnBola = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel1.setText("Masukan panjang :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 31, 140, 30);
        jPanel1.add(tbPBalok);
        tbPBalok.setBounds(150, 30, 220, 30);
        jPanel1.add(tbLBalok);
        tbLBalok.setBounds(150, 70, 220, 30);

        jLabel2.setText("Masukan lebar :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 140, 30);

        jLabel3.setText("Masukan tinggi :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 110, 140, 30);
        jPanel1.add(tbTBalok);
        tbTBalok.setBounds(150, 110, 220, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("cm");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(380, 110, 60, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("cm");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(380, 30, 60, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("cm");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(380, 70, 60, 30);

        BtnBalok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        BtnBalok.setText("Hitung");
        BtnBalok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBalokActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBalok);
        BtnBalok.setBounds(150, 160, 100, 40);

        jTabbedPane1.addTab("Balok", jPanel1);

        jPanel2.setLayout(null);

        jLabel7.setText("Masukan panjang sisi :");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 31, 140, 30);
        jPanel2.add(tbPKubus);
        tbPKubus.setBounds(150, 30, 220, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("cm");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(380, 30, 60, 30);

        btnKubus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKubus.setText("Hitung");
        btnKubus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKubusActionPerformed(evt);
            }
        });
        jPanel2.add(btnKubus);
        btnKubus.setBounds(150, 80, 100, 40);

        jTabbedPane1.addTab("Kubus", jPanel2);

        jPanel3.setLayout(null);

        jLabel9.setText("Masukan jari-jari :");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(10, 31, 140, 30);
        jPanel3.add(tbJBola);
        tbJBola.setBounds(150, 30, 220, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("cm");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(380, 30, 60, 30);

        btnBola.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBola.setText("Hitung");
        btnBola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolaActionPerformed(evt);
            }
        });
        jPanel3.add(btnBola);
        btnBola.setBounds(150, 80, 100, 40);

        jTabbedPane1.addTab("Bola", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(10, 40, 450, 280);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBalokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBalokActionPerformed
        // TODO add your handling code here:
        
        int panjang, lebar, tinggi;
        panjang = Integer.parseInt(tbPBalok.getText());
        lebar = Integer.parseInt(tbLBalok.getText());
        tinggi = Integer.parseInt(tbTBalok.getText());
        int hasil = panjang * lebar * tinggi;
        
        try {
            JOptionPane.showMessageDialog(null, "Volume balok adalah : " + hasil, "luas",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error : "+e,"Gagal", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BtnBalokActionPerformed

    private void btnKubusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKubusActionPerformed
        // TODO add your handling code here:
        int sisi;
        sisi = Integer.parseInt(tbPKubus.getText());
        int hasil = sisi * sisi * sisi;
        
        try {
            JOptionPane.showMessageDialog(null, "Luas Permukaan kubus adalah :"+hasil,"luas", JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnKubusActionPerformed

    private void btnBolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolaActionPerformed
        // TODO add your handling code here:
        float jari;
        jari = Integer.parseInt(tbJBola.getText());
        float hasil = (float) (4.3*3.14*jari*jari*jari);
        
        try {
            JOptionPane.showMessageDialog(null, "Luas permukaan bola adalah :"+hasil,"luas",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error :"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBolaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBalok;
    private javax.swing.JButton btnBola;
    private javax.swing.JButton btnKubus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField tbJBola;
    private javax.swing.JTextField tbLBalok;
    private javax.swing.JTextField tbPBalok;
    private javax.swing.JTextField tbPKubus;
    private javax.swing.JTextField tbTBalok;
    // End of variables declaration//GEN-END:variables
}
